// Custom shader file for rungolem-5-16.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

rungolem-5-16/705D6E5A4974579F8B07896FAA260CBB
{ // Q3Map2 defaulted
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/pipe2_7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/A36851DD48A1283ED2DAF653F8BB8F66
{ // Q3Map2 defaulted
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/pipe2_7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/2E385E2F28EF408630A04430363D3244
{ // Q3Map2 defaulted
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/pipe2_7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/20CE940E8385D9E3BF1B22DB7F2E684C
{ // Q3Map2 defaulted
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/pipe2_7.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/058728F6C9660A14EC77F32A9026CE6B
{ // Q3Map2 defaulted
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/floor2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/F680988D015FCA59146C98458B9A7EB8
{ // Q3Map2 defaulted
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.25781 0.00000
	}

	{
		map textures/rungolem/floor2stripe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/0DF2C6DF4F53E55F7248055729C88D9B
{ // Q3Map2 defaulted
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/pipe1_5.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/87B1E31477E2223347860B16274D4622
{ // Q3Map2 defaulted
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/pipe1_5.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/FCD231995E83A6086A87754A707F5E1B
{ // Q3Map2 defaulted
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/pipe1_5.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/F767AB98EBFE63B8F29BD0ADCD86A357
{ // Q3Map2 defaulted
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/floor1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/E1D37FDB416D4EA3146A1F0E88329B64
{ // Q3Map2 defaulted
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/starc.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/B800D0E03D952B30AAB111B6AAF1A446
{ // Q3Map2 defaulted
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metpan_caution.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/51E800476CDD56B76EDC5C4100019404
{ // Q3Map2 defaulted
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metpan_caution.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/44C6E3D083D4842950CD565D5E4EB90E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metpan_caution.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/032E4D5D96C59E6787DA903F658045CA
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/concrete0dark.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/9050C342283F95452035F7AE02793E6F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/concrete0dark.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/486BEDDAA408789FD872DB4905650D3C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/concrete0dark.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/4958D7A76DC3413EBAFDED8F9B045182
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/concrete0dark.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/95E3B72B172094D7B3BD583912B4021B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/concrete0dark.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/7B9DF9BD298492D20ABBE015D8E0D496
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/concrete0dark.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/542A2CE5C074FB2BF157605A8BC53DF6
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/concrete0dark.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/00BD6D23E7FBED00C0600BCE963EF96D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/concrete0dark.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/825CD236B95F6D118BB62021A1C97B28
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/concrete0.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/275ACC47219D0B99B3E9369F5DBC99F3
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/concrete0.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/B5E0DB1DF19FDFB5690EFC1002228F57
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/stair1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/D88F7B7BA791683E71DA6C50DF926951
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/stair1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/E54B2D37A76981532C93EB298F4DBBAC
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/stair1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/D7EE9120554F45FF6910BAD39E7FAA64
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/stair1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/687FDFC536FF0F674AF63BE63507F0AA
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/stair1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/0C0C1D13E5D43A2523E607F3310C3D29
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0017.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/stair1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/A322B5A4883CF1A6E972FAF666B45D5A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/stair1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/3D449D9446DF4AAD44FBB73C67AD587E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metpan5.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/97BF59DEF7BBFB6AA027179051E22357
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metpan5.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/589463A77A6E89361383344E3EA3C554
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metpan2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/948B69F8B6B15F82EA39BA688795903B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.31250 0.00000
	}

	{
		map textures/rungolem/metpan2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/4BAFF0FFD2EBCBA066B0E00F5C7D7FB8
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metpan2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/4E7C8DCD252A6406A109D979FC3E4475
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/floor1stripe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/7D942B8BE21ACEE67F9D5D989827F271
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/floor1stripe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/58F7EA784CB80DC99249BAF772D89887
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/floor1stripe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/C69520973955A610E33E3AC1BB1695AA
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/floor1stripe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/A96329E5A371FA57A7154AB04EF4A329
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/floor1stripe.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/C7863A0F829ABB255494E4E689119ABF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0013.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metglu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/BFBD616910D7024FB5BD3D6FF7D7444A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metglu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/CFF0BD377FF2833A9FD9ED269807A897
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metglu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/462BE82E99DA499E62C586D13939A2C4
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metglu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/073CA4967AFC149824DA102253908535
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metglu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/1CC24D21B359E8716A7DD3BA9CFD92C2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metglu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/1F901BEA9B472A8B8FF92D374678C91C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metglu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/13222F2751253CC7CFCEF00E72075305
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metglu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/30D4D9F747469418977335584DA06409
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metglu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/4B1448C52BFF99775C96AD16E2DE8C8A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metglu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/CADD4A72E6DF8F139A0C871727368C5A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metglu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/7A71AA4C884DA653AD0E5627CF05EEAE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 -0.50000
	}

	{
		map textures/rungolem/metglu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/D95FFA03E69FB9DD46F778260F5A7D9A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metglu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/C1D42C4684DB73818D698851A95EE382
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/rungolem/metglu.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/832F3210FC671C1A02D7E82997188BC8
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metpan5.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

rungolem-5-16/ED782C554B5E60D95DF03F15A771C850
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/rungolem-5-16/lm_0013.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 2
		tcGen lightmap
	}

	{
		map textures/rungolem/metpan5.tga
		blendFunc GL_DST_COLOR GL_ZERO
		lightstage
	}
}

